# Generated by Django 3.0.3 on 2020-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmodel',
            name='author',
            field=models.CharField(default='格格', max_length=255),
        ),
        migrations.AddField(
            model_name='imgmodel',
            name='category',
            field=models.CharField(default='油画，油画棒，丙烯，彩铅', max_length=255),
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='comment',
            field=models.TextField(default='一句话想法'),
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='datas',
            field=models.ImageField(upload_to='imgs/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='imgmodel',
            name='title',
            field=models.CharField(default='画画', max_length=255),
        ),
    ]
